### ISSUE TITLE
Hello,Author, I wonder where the files stoplist.txt and train_data.txt are?

### ISSUE THREAD

**Issue by MrLeeYiXiu** [zfjsail/OAG#1]
I am very glad to read your article. When I was preparing to further simulate your experiment, I found a bug in the program, because the files stoplist.txt and train_data.txt were missing. I hope you can upload these two files, thank you.

**Comment by andremann** [comment]
Several files are missing. In the readme, the authors stated the repo is under construction, so let's wait patiently to have all the assets :)

**Comment by MrLeeYiXiu** [comment]
Thanks for your reply. I will wait.

**Comment by zfjsail** [comment]
Hello, please see the uploaded datasets described in the readme. Thanks.
